version: '3.8'
services:
  estudamais_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: user92/frontend-estudamais:latest
    ports:
      - "8503:80"
    restart: unless-stopped
    container_name: estudamais_frontend
