name: CI EstudaMais Frontend

on:
  push:
    branches: [ "main", "develop" ] # Gatilhos para branches main e develop
  pull_request:
    branches: [ "main", "develop" ] # Gatilhos para PRs para main e develop

jobs:
  build_and_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Testar com algumas versões do Node

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache para dependências npm

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    # Opcional: Adicionar etapa de teste se você tiver testes
    # - name: Run tests
    #   run: npm test
