name: Build & Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            set -e

            cd ~/frontend-estudamais

            # 1) Sincroniza o main sem conflitos
            git fetch origin main
            git reset --hard origin/main

            # 2) Para e remove o container antigo (libera a porta 8503)
            docker-compose down

            # 3) Rebuild & Up
            docker-compose up -d --build

            # 4) Opcional: limpa imagens obsoletas
            docker image prune -f
